package com.contentruck.hypofit.interview.service;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

public record InterviewPostWriteModel(
        UUID id,
        UUID founderId,
        String recruitmentType,
        String title,
        String serviceSummary,
        String targetDescription,
        Integer rewardAmount,
        List<PostingCompensation> compensations,
        Integer durationMinutes,
        Integer recruitCount,
        String externalProvider,
        String externalUrl,
        OffsetDateTime participationDeadlineAt,
        String externalDataNotice,
        List<String> betaTestPlatforms,
        OffsetDateTime betaTestStartsAt,
        OffsetDateTime betaTestEndsAt,
        String interviewMode,
        String location,
        String locationText,
        String locationAddress,
        String locationPlaceName,
        Double locationLatitude,
        Double locationLongitude,
        String locationPrecision,
        String locationSource,
        List<String> scheduleOptions,
        String status,
        OffsetDateTime createdAt,
        String entryMode,
        List<String> participantRequirements,
        PostingCreationConfiguration creationConfiguration
) {
    public InterviewPostWriteModel(
            UUID id,
            UUID founderId,
            String recruitmentType,
            String title,
            String serviceSummary,
            String targetDescription,
            Integer rewardAmount,
            Integer durationMinutes,
            Integer recruitCount,
            String externalProvider,
            String externalUrl,
            OffsetDateTime participationDeadlineAt,
            String externalDataNotice,
            List<String> betaTestPlatforms,
            OffsetDateTime betaTestStartsAt,
            OffsetDateTime betaTestEndsAt,
            String interviewMode,
            String location,
            String locationText,
            String locationAddress,
            String locationPlaceName,
            Double locationLatitude,
            Double locationLongitude,
            String locationPrecision,
            String locationSource,
            List<String> scheduleOptions,
            String status,
            OffsetDateTime createdAt
    ) {
        this(
                id, founderId, recruitmentType, title, serviceSummary, targetDescription,
                rewardAmount, PostingCompensations.legacy(rewardAmount == null ? 0 : rewardAmount),
                durationMinutes, recruitCount, externalProvider, externalUrl, participationDeadlineAt,
                externalDataNotice, betaTestPlatforms, betaTestStartsAt, betaTestEndsAt,
                interviewMode, location, locationText, locationAddress, locationPlaceName,
                locationLatitude, locationLongitude, locationPrecision, locationSource,
                scheduleOptions, status, createdAt, "application_required", List.of(),
                PostingCreationConfiguration.empty()
        );
    }
    public InterviewPostWriteModel(
            UUID id,
            UUID founderId,
            String recruitmentType,
            String title,
            String serviceSummary,
            String targetDescription,
            Integer rewardAmount,
            Integer durationMinutes,
            Integer recruitCount,
            String interviewMode,
            String location,
            String locationText,
            String locationAddress,
            String locationPlaceName,
            Double locationLatitude,
            Double locationLongitude,
            String locationPrecision,
            String locationSource,
            List<String> scheduleOptions,
            String status,
            OffsetDateTime createdAt
    ) {
        this(
                id,
                founderId,
                recruitmentType,
                title,
                serviceSummary,
                targetDescription,
                rewardAmount,
                PostingCompensations.legacy(rewardAmount == null ? 0 : rewardAmount),
                durationMinutes,
                recruitCount,
                null,
                null,
                null,
                null,
                List.of(),
                null,
                null,
                interviewMode,
                location,
                locationText,
                locationAddress,
                locationPlaceName,
                locationLatitude,
                locationLongitude,
                locationPrecision,
                locationSource,
                scheduleOptions,
                status,
                createdAt,
                "application_required",
                List.of(),
                PostingCreationConfiguration.empty()
        );
    }
}
