package com.contentruck.hypofit.interview.service;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

public record InterviewPostReadModel(
        UUID id,
        UUID founderId,
        String recruitmentType,
        String entryMode,
        String title,
        String serviceSummary,
        String targetDescription,
        int rewardAmount,
        List<PostingCompensation> compensations,
        int durationMinutes,
        int recruitCount,
        String externalProvider,
        String externalUrl,
        OffsetDateTime participationDeadlineAt,
        String externalDataNotice,
        List<String> betaTestPlatforms,
        OffsetDateTime betaTestStartsAt,
        OffsetDateTime betaTestEndsAt,
        String interviewMode,
        String location,
        String locationText,
        String locationAddress,
        String locationPlaceName,
        Double locationLatitude,
        Double locationLongitude,
        String locationPrecision,
        String locationSource,
        List<String> scheduleOptions,
        String status,
        OffsetDateTime createdAt,
        FounderSummary founder,
        FounderReviewSummary founderReviewSummary,
        Double distanceMeters,
        InterviewAiSummaryReadModel aiSummary,
        List<String> participantRequirements,
        PostingCreationConfiguration creationConfiguration
) {
    public InterviewPostReadModel(
            UUID id,
            UUID founderId,
            String recruitmentType,
            String title,
            String serviceSummary,
            String targetDescription,
            int rewardAmount,
            int durationMinutes,
            int recruitCount,
            String externalProvider,
            String externalUrl,
            OffsetDateTime participationDeadlineAt,
            String externalDataNotice,
            List<String> betaTestPlatforms,
            OffsetDateTime betaTestStartsAt,
            OffsetDateTime betaTestEndsAt,
            String interviewMode,
            String location,
            String locationText,
            String locationAddress,
            String locationPlaceName,
            Double locationLatitude,
            Double locationLongitude,
            String locationPrecision,
            String locationSource,
            List<String> scheduleOptions,
            String status,
            OffsetDateTime createdAt,
            FounderSummary founder,
            FounderReviewSummary founderReviewSummary,
            Double distanceMeters,
            InterviewAiSummaryReadModel aiSummary
    ) {
        this(
                id, founderId, recruitmentType, "application_required", title, serviceSummary, targetDescription,
                rewardAmount, PostingCompensations.legacy(rewardAmount), durationMinutes,
                recruitCount, externalProvider, externalUrl, participationDeadlineAt,
                externalDataNotice, betaTestPlatforms, betaTestStartsAt, betaTestEndsAt,
                interviewMode, location, locationText, locationAddress, locationPlaceName,
                locationLatitude, locationLongitude, locationPrecision, locationSource,
                scheduleOptions, status, createdAt, founder, founderReviewSummary, distanceMeters,
                aiSummary,
                List.of(),
                PostingCreationConfiguration.empty()
        );
    }
    public InterviewPostReadModel(
            UUID id,
            UUID founderId,
            String recruitmentType,
            String title,
            String serviceSummary,
            String targetDescription,
            int rewardAmount,
            int durationMinutes,
            int recruitCount,
            String externalProvider,
            String externalUrl,
            OffsetDateTime participationDeadlineAt,
            String externalDataNotice,
            List<String> betaTestPlatforms,
            OffsetDateTime betaTestStartsAt,
            OffsetDateTime betaTestEndsAt,
            String interviewMode,
            String location,
            String locationText,
            String locationAddress,
            String locationPlaceName,
            Double locationLatitude,
            Double locationLongitude,
            String locationPrecision,
            String locationSource,
            List<String> scheduleOptions,
            String status,
            OffsetDateTime createdAt,
            FounderSummary founder,
            FounderReviewSummary founderReviewSummary,
            Double distanceMeters
    ) {
        this(
                id,
                founderId,
                recruitmentType,
                "application_required",
                title,
                serviceSummary,
                targetDescription,
                rewardAmount,
                PostingCompensations.legacy(rewardAmount),
                durationMinutes,
                recruitCount,
                externalProvider,
                externalUrl,
                participationDeadlineAt,
                externalDataNotice,
                betaTestPlatforms,
                betaTestStartsAt,
                betaTestEndsAt,
                interviewMode,
                location,
                locationText,
                locationAddress,
                locationPlaceName,
                locationLatitude,
                locationLongitude,
                locationPrecision,
                locationSource,
                scheduleOptions,
                status,
                createdAt,
                founder,
                founderReviewSummary,
                distanceMeters,
                null,
                List.of(),
                PostingCreationConfiguration.empty()
        );
    }

    public InterviewPostReadModel(
            UUID id,
            UUID founderId,
            String recruitmentType,
            String title,
            String serviceSummary,
            String targetDescription,
            int rewardAmount,
            int durationMinutes,
            int recruitCount,
            String interviewMode,
            String location,
            String locationText,
            String locationAddress,
            String locationPlaceName,
            Double locationLatitude,
            Double locationLongitude,
            String locationPrecision,
            String locationSource,
            List<String> scheduleOptions,
            String status,
            OffsetDateTime createdAt,
            FounderSummary founder,
            FounderReviewSummary founderReviewSummary,
            Double distanceMeters,
            InterviewAiSummaryReadModel aiSummary
    ) {
        this(
                id,
                founderId,
                recruitmentType,
                "application_required",
                title,
                serviceSummary,
                targetDescription,
                rewardAmount,
                PostingCompensations.legacy(rewardAmount),
                durationMinutes,
                recruitCount,
                null,
                null,
                null,
                null,
                List.of(),
                null,
                null,
                interviewMode,
                location,
                locationText,
                locationAddress,
                locationPlaceName,
                locationLatitude,
                locationLongitude,
                locationPrecision,
                locationSource,
                scheduleOptions,
                status,
                createdAt,
                founder,
                founderReviewSummary,
                distanceMeters,
                aiSummary,
                List.of(),
                PostingCreationConfiguration.empty()
        );
    }
}
